
language: php

php:
    - 5.5
    - 5.6
    - 7.0

services:
    - mysql
    - postgresql

before_script:
    - createdb -Upostgres -EUTF-8 -Ttemplate0 zapstore_test_db
    - mysql -e 'CREATE DATABASE zapstore_test_db'
    - composer install -no --prefer-dist

script:
    - php ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php tests

after_success:
    - curl -s https://codecov.io/bash | bash

