
language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_script:
    - composer install -no --prefer-dist

script:
    - php ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php tests

after_success:
    - curl -s https://codecov.io/bash | bash

